### ISSUE TITLE
0.0.10 release?

### ISSUE THREAD

**Issue by jakirkham** [pitrou/pickle5-backport#17]
Just saw PR ( https://github.com/pitrou/pickle5-backport/pull/16 ) landed with a backport of the fix from issue ( https://bugs.python.org/issue39492 ). Would it be possible to get a patch release with this fix?

FWIW this would be helpful for adding `pickle5` support to `cloudpickle` ( https://github.com/cloudpipe/cloudpickle/pull/370 ) :)

**Comment by pitrou** [comment]
I'll see about that in a couple of days.

**Comment by pitrou** [comment]
Ok, I've released 0.10.0 now. Feel free to point any problems.

**Comment by pitrou** [comment]
cc @pcmoritz

**Comment by jakirkham** [comment]
Awesome! Thanks Antoine! 😄

**Comment by pcmoritz** [comment]
This is awesome, thanks Antoine!

**Comment by jakirkham** [comment]
Also on conda-forge now.
