### ISSUE TITLE
PickleBuffer tp_name references pickle (not pickle5)

### ISSUE THREAD

**Issue by jakirkham** [pitrou/pickle5-backport#19]
It appears that `PickleBuffer`'s [`tp_name` references the `pickle` module]( https://github.com/pitrou/pickle5-backport/blob/c0c1a158f59366696161e0dffdd10cfe17601372/pickle5/picklebufobject.c#L210 ) and not `pickle5`.

**Comment by jakirkham** [comment]
Similar observations can be made of `tp_name` and `m_name` in `_pickle`.

**Comment by jakirkham** [comment]
Have submitted PR ( https://github.com/pitrou/pickle5-backport/pull/20 ).

**Comment by pitrou** [comment]
I've made a [release](https://pypi.org/project/pickle5/0.0.11/) with this fix.

**Comment by jakirkham** [comment]
That's great! Thank you Antoine! 😄

**Comment by jakirkham** [comment]
Also [published on conda-forge]( https://anaconda.org/conda-forge/pickle5/files?version=0.0.11 ).
