### ISSUE TITLE
Pickle5 Not working in CentOS 7 Python 3.6.8

### ISSUE THREAD

**Issue by R-I-S-Khan** [pitrou/pickle5-backport#21]
I am using pip to install pickle5 on CentOS 7 and using python 3.6.8.

`
pip install pickle5
`

I am getting an error.
![image](https://user-images.githubusercontent.com/28854577/88307317-cac37c80-ccd9-11ea-8777-25b82972915b.png)

**Comment by pitrou** [comment]
You must install the Python development headers. It's probably called python-dev or python3-dev or something like that...
