### ISSUE TITLE
pickle5 install on Win10 fails due to allegedly missing MS Visual C++14.0

### ISSUE THREAD

**Issue by dervisbey** [pitrou/pickle5-backport#22]
Hello!

I am trying to install pickle5 on my Windows 10 machine and python 3.6 environment. I fail though because of following error:

`"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"`

But **I do have Visual C++ 14.0**. All other packages, like spacy e.g., that require Visual C++ 14 dont return an error when installing.
Also, installing Visual C++ 14.0 again is not an option for me, as I dont have the permission to install it again on this machine.

Best,
Edit: This is the exact error message (sry fromat is terrible, i don't know why):

Collecting pickle5
  Using cached pickle5-0.0.11.tar.gz (132 kB)
Building wheels for collected packages: pickle5
  Building wheel for pickle5 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\envs\ma36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\-----\\AppData\\Local\\Temp\\pip-install-z5xjt3q3\\pickle5\\setup.py'"'"'; __file__='"'"'C:\\Users\\-----\\AppData\\Local\\Temp\\pip
-install-z5xjt3q3\\pickle5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\-----\AppData\Local\Temp\pip-wheel-i
dmg0scx'
       cwd: C:\Users\-----\AppData\Local\Temp\pip-install-z5xjt3q3\pickle5\
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pickle5
  copying pickle5\pickle.py -> build\lib.win-amd64-3.6\pickle5
  copying pickle5\pickletools.py -> build\lib.win-amd64-3.6\pickle5
  copying pickle5\__init__.py -> build\lib.win-amd64-3.6\pickle5
  creating build\lib.win-amd64-3.6\pickle5\test
  copying pickle5\test\pickletester.py -> build\lib.win-amd64-3.6\pickle5\test
  copying pickle5\test\test_pickle.py -> build\lib.win-amd64-3.6\pickle5\test
  copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-3.6\pickle5\test
  copying pickle5\test\__init__.py -> build\lib.win-amd64-3.6\pickle5\test
  running build_ext
  building 'pickle5._pickle' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
**ERROR: Failed building wheel for pickle5**
  Running setup.py clean for pickle5
**Failed to build pickle5**
Installing collected packages: pickle5
    **Running setup.py install for pickle5 ... error**
    **ERROR: Command errored out with exit status 1:**
     command: 'c:\programdata\anaconda3\envs\ma36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-z5xjt3q3\\pickle5\\setup.py'"'"'; __file__='"'"'C:\\Users\\****\\AppData\\Local\\Temp\\p
ip-install-z5xjt3q3\\pickle5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\****\AppData\Local\Temp\pip-rec
ord-_b4ym60d\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\programdata\anaconda3\envs\ma36\Include\pickle5'
         cwd: C:\Users\****\AppData\Local\Temp\pip-install-z5xjt3q3\pickle5\
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pickle5
    copying pickle5\pickle.py -> build\lib.win-amd64-3.6\pickle5
    copying pickle5\pickletools.py -> build\lib.win-amd64-3.6\pickle5
    copying pickle5\__init__.py -> build\lib.win-amd64-3.6\pickle5
    creating build\lib.win-amd64-3.6\pickle5\test
    copying pickle5\test\pickletester.py -> build\lib.win-amd64-3.6\pickle5\test
    copying pickle5\test\test_pickle.py -> build\lib.win-amd64-3.6\pickle5\test
    copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-3.6\pickle5\test
    copying pickle5\test\__init__.py -> build\lib.win-amd64-3.6\pickle5\test
    running build_ext
    building 'pickle5._pickle' extension
    **error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/**
    ----------------------------------------
**ERROR: Command errored out with exit status 1**: 'c:\programdata\anaconda3\envs\ma36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-z5xjt3q3\\pickle5\\setup.py'"'"'; __file__='"'"'C:\\Users
\\****\\AppData\\Local\\Temp\\pip-install-z5xjt3q3\\pickle5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\
****\AppData\Local\Temp\pip-record-_b4ym60d\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\programdata\anaconda3\envs\ma36\Include\pickle5' Check the logs for full command output.

**Comment by Artificial-Incoherence** [comment]
Facing same Issue in my system.

**Comment by pitrou** [comment]
I have absolutely no idea why this happens. However, since you seem to be using Anaconda, you can just install pickle5 from conda-forge (or perhaps from Anaconda itself): `conda install -c conda-forge pickle5`.

**Comment by Artificial-Incoherence** [comment]
> I have absolutely no idea why this happens. However, since you seem to be using Anaconda, you can just install pickle5 from conda-forge (or perhaps from Anaconda itself): `conda install -c conda-forge pickle5`.

But I don't have any anaconda environment, then why this happens to me also?

**Comment by pitrou** [comment]
Sorry, I was answering the OP. That said, I don't think it's Anaconda-related. Perhaps you need to call Visual Studio's activation script before running `pip install pickle5`?

**Comment by pitrou** [comment]
A Google search gives many results for this error message. Apparently one of the suggestion is to `pip install --upgrade setuptools` first.
