### ISSUE TITLE
Release prebuilt manylinux wheels on pypi

### ISSUE THREAD

**Issue by sighingnow** [pitrou/pickle5-backport#24]
Hi @pitrou,

Could be upload wheels built by manylinux environment to pypi for pickle5 to reduce the extra depencencies (python development package) for end users?

It that suites for you I could help, if needed.

Thanks in advance!

**Comment by sighingnow** [comment]
I have also noticed complaint like #21.

**Comment by pitrou** [comment]
@sighingnow It's very unlikely to happen, unless you contribute some tooling that would make this mostly effortless.
