### ISSUE TITLE
pickle5 fails to dump pandas.core.indexes.numeric.Int64Index on Mac, but works on Linux

### ISSUE THREAD

**Issue by sighingnow** [pitrou/pickle5-backport#25]
The following code fails on Mac:

```python
>>> import pandas
>>> import pickle5
>>> x = pandas.core.indexes.numeric.Int64Index([1,2,3,4,5])
>>> pickle5.dumps(x, 5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-dc361641ea41> in <module>
----> 1 pickle5.dumps(x, 5)

TypeError: cannot pickle 'pickle.PickleBuffer' object
>>> pandas.__version__
'1.1.5'
```

Version of python: 3.9.2
Version of pickle5: 0.0.11

But the same code works well on Linux with Python 3.8, using the same version of pandas and pickle5. The only difference is version of Python, but I think that shouldn't be a problem :)

**Comment by jakirkham** [comment]
Python 3.8+ already has builtin support for pickle protocol 5. Would just use that instead of the backport package

**Comment by sighingnow** [comment]
This issue breaks pyarrow, since it prefers pickle5 when it importable:

https://github.com/apache/arrow/blob/939195183657daa2060970b6fcd1938eab53d44b/python/pyarrow/compat.pxi#L42-L46

Or, we at least should make `pickle5-backport` un-installable for Python 3.8+. I could submit such a pull request after knows @pitrou's comment on this ticket.

**Comment by sighingnow** [comment]
> This issue breaks pyarrow, since it prefers pickle5 when it importable:
> 
> https://github.com/apache/arrow/blob/939195183657daa2060970b6fcd1938eab53d44b/python/pyarrow/compat.pxi#L42-L46
> 
> Or, we at least should make `pickle5-backport` un-installable for Python 3.8+. I could submit such a pull request after knows @pitrou's comment on this ticket.

Or, forward to builtin-pickle for python 3.8+, for compatibility reason.

**Comment by pitrou** [comment]
But PyArrow doesn't depend on `pickle5`. Surely you installed `pickle5` yourself?

**Comment by pitrou** [comment]
Also, I'm not sure how to prevent `pip` from installing `pickle5` on Python 3.8...

**Comment by jakirkham** [comment]
I think adding something like 

```
python_requires=">3.4,<3.8"
```
 
to `setup.py` should work (though haven’t tested it)

**Comment by sighingnow** [comment]
> But PyArrow doesn't depend on `pickle5`. Surely you installed `pickle5` yourself?

I'm not sure, but it is there.

> Also, I'm not sure how to prevent pip from installing pickle5 on Python 3.8...

I think [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) could do the trick, which requires pip>=9.0.0, which should be reasonable.

**Comment by pitrou** [comment]
Ok, feel free to submit a PR then :-)
