### ISSUE TITLE
pickle5 pip install failing on m1 mac

### ISSUE THREAD

**Issue by stevenhurwitt** [pitrou/pickle5-backport#28]
Hi,

I'm using an m1 mac (apple silicon) and attempting to install pickle5 using pip for python 3.7.10. I'm using pyenv to access python 3.7, but am using a virtualenv trying to build pyarrow from source (this seems like it could be causing an issue).

Logs are attached, any help or advice would be appreciated.

[pickle5.log](https://github.com/pitrou/pickle5-backport/files/7188833/pickle5.log)

**Comment by pitrou** [comment]
It seems like you're using PyPy. pickle5 is not supported on PyPy.

**Comment by stevenhurwitt** [comment]
ah, got it! thanks i'll close the issue
