### ISSUE TITLE
Increase extensibility of pickle5's C-Pickler

### ISSUE THREAD

**Issue by pierreglaser** [pitrou/pickle5-backport#8]
Follow up on: https://github.com/cloudpipe/cloudpickle/pull/253#issuecomment-475731931
It would be nice to have `cloudpickle` use the `pickle5-backport` C-Pickler on `Python` < `3.8`, for 2 reasons:
- use protocol 5 on older `Python` versions.
- make `cloudpickle` faster by using `pickle5`'s CPickler instead of the pythonic `Pickler` on those older versions.

@pitrou would you be ok with integrating the recent changes  of the `Python3.8`'s `pickle` into `pickle5`?

**Comment by pitrou** [comment]
@pierreglaser @suquark @pcmoritz I've just released version 0.0.9 on PyPI, FYI.

**Comment by pierreglaser** [comment]
Thank you!
