### ISSUE TITLE
'reducer_override' support

### ISSUE THREAD

**Issue by suquark** [pitrou/pickle5-backport#9]
Currently, the python3.8.0b4 (https://github.com/python/cpython/releases/tag/v3.8.0b4) has `reducer_override` support in struct `PicklerObject`, which makes inheriting from cpython `Pickler` feasible. It could also help #8. I think it is important because there is about 20x performance gap between the cpython version and the pure python version.

**Comment by pitrou** [comment]
Fixed by PR #11.
